language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
# command to install dependencies
before_install: "cd tests"
install: "./install.sh"
# command to run tests
script: "coverage run --source=webpack_loader manage.py test"
after_success:
  - coverage xml
  - cp coverage.xml ../
  - coveralls
env:
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8
