language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
# command to install dependencies
before_install: "cd tests"
install: "./install.sh"
# command to run tests
script: "coverage run --source=tests manage.py test"
after_success:
  coveralls
